FROM resin/%%RESIN_MACHINE_NAME%%-node

ENV INITSYSTEM on

WORKDIR /usr/src/app

COPY package.json .

RUN JOBS=MAX npm install --unsafe-perm --production && npm cache clean

COPY . ./

CMD node src/app.js
